### ISSUE TITLE
Need more info on how to do the training?

### ISSUE THREAD

**Issue by nithyadurai87** [harish2704/pottan-ocr#15]
I am trying to train for tamil fonts.

created this repo.
https://github.com/nithyadurai87/pottan-ocr-tamil

https://github.com/nithyadurai87/pottan-ocr-tamil/blob/master/config.yaml
added this file.

It seems the install step for training needs GPU, CUDA etc.
when installing them and enabling the NVDIA driver, my ubuntu got crashed.
reinstalled ubuntu.

Is there any way to train on cloud?
You used  Floydhub.

Requesting you to add tutorial on how to train using floudhub.

Thanks.

**Comment by harish2704** [comment]
Hi @nithyadurai87, 
Regarding your questions:
1. Ubuntu crashing while installing Nvidia driver.
  Sorry, I can't comment anything about this now. Because, I didn't had owned a real Nvidia GPU till now, I usually uses cloud services which provides ready to use containers for ML development.

2. >> Is there any way to train on cloud?
Yes. There are many ways, there are many cloud providers which provides GPU containers for ML workloads. Google colab, Floydhub, Paperspace, GPUEater etc are few of them.

3. >> Requesting you to add tutorial on how to train using floudhub
    * A Floydhub project is a self contained source tree. That means, If you can see a Floydhub project, you will be able to replicate it yourself on Floydhub.
    * Please take a look at https://www.floydhub.com/harish2704/projects/testbed/6 which is a initial training session of pottan OCR, ( That is, other training sessions uses data generated by this training session and thus we can say other sessions depends on this training session )
    * As you can see this image, ![image](https://user-images.githubusercontent.com/1652903/58339530-6e5f9580-7e67-11e9-8148-87a4d0d1a3cc.png) the command used to run this training session is `floyd run --gpu --env pytorch-0.3 --data harish2704/datasets/pottan-ocr/1:/basedeps --data harish2704/datasets/pottan-ocr/2:/datadeps 'bash bootstrap.sh'`
    * As you can clearly see from the command, the bootstrap script can be accessed here https://www.floydhub.com/harish2704/projects/testbed/6/code/bootstrap.sh which actually contains some shell commands to automatically install and setup required dependencies.

**Comment by harish2704** [comment]
Also, if you are a hacker, I would suggest to try Google colab, which is a free service provided by google.
You can run tasks continuously for 12 hour on google cloud in a single stretch. After that you may have to restart the job, but that will be more than enough for this project. Because, the latest trained model is a product of 1:30 - 2:00 hour training on V100 GPU

**Comment by harish2704** [comment]
I also forgot to mention that, there is a branch called  [floyd_hub](https://github.com/harish2704/pottan-ocr/tree/floyd_hub) available in this repo.
I kept that branch to keep any modifications specific to Floydhub training.
